#server:
#  port: 8211
#spring:
#  application:
#    name: service-cmn
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://182.42.109.129:3306/yygh_hosp?characterEncoding=utf-8&useSSL=false
#    username: root
#    password: dlq.*123
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 182.42.109.129:8848
#  redis:
#    host: 182.42.109.129
#    port: 6379
#    password: dlq.*123
#    database: 5
#    timeout: 1800000
#    lettuce:
#      pool:
#        max-active: 20
#        max-wait: -1 #最大阻塞等待时间(负数表示没限制)
#        max-idle: 5
#        min-idle: 0
