#server:
#  port: 8212
#spring:
#  application:
#    name: service-user
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://182.42.109.129:3306/yygh_user?characterEncoding=utf-8&useSSL=false
#    username: root
#    password: dlq.*123
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 182.42.109.129:8848
#  data:
#    mongodb:
#      uri: mongodb://yygh_hosp:dlq.*123@182.42.109.129:27017/yygh_hosp
#  session:
#    store-type: redis
#wx:
#  open:
#    app-id: wxed9954c01bb89b47
#    app-secret: a7482517235173ddb4083788de60b90e
#    redirect-uri: http://guli.shop/api/ucenter/wx/callback
#    base-uri: http://localhost:3000
