#server:
#  port: 9110 # 服务端口
#
#spring:
#  profiles:
#    active: dev # 环境设置
#  application:
#    name: service-gateway # 服务名
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 182.42.109.129:8848 # nacos服务地址
#    gateway:
#      discovery:
#        locator:
#          enabled: true # gateway可以发现nacos中的微服务
#      routes:
#        - id: service-edu
#          uri: lb://service-edu
#          predicates:
#            - Path=/*/edu/**,/eduservice/**

