#server:
#  port: 8216
#spring:
#  application:
#    name: service-task
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#  rabbitmq:
#    host: 182.42.109.129
#    port: 5672
#    username: saber
#    password: dlq.*123
#    virtual-host: /
