#server:
#  port: 8217
#spring:
#  application:
#    name: service-statistics
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/yygh_order?characterEncoding=utf-8&useSSL=false
#    username: root
#    password: root
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
